### PR TITLE
Add `ast.AsyncFunctionDef` to correctly recognize async test methods.

### LINKED ISSUE #62: async test for method in class not discovered.
Hi, I wonder if you can help me in this situation.

I want to have a class and do async tests. If I run my tests with pytest in the command line and also by using unittest, this code runs, but, pycrunch seems not to discover (or maybe my error is other).

In this image, if the word 'async' is *ommited*, the test is shown and executed (incorrectly)

pycrunch

If I make it work, as an async test, the test is not discovered:

pycrunch2

I also tryed the recommended code in:
https://github.com/gleb-sevruk/pycrunch-engine/issues/52

but is not discovered, or maybe I need some special config.

pycrunch3

Thank you very much in advanced.
(BTW, very cool tool!!!)

### PR DESCRIPTION
**Pull request by accoleon**
- Added `ast.AsyncFunctionDef` to discovery
- Tested on my own code, while existing tests pass (other than the 5 failing ones that happened on fork)

Resolves #62

### CODE REVIEW

**Comment by gleb-sevruk** [comment]
Great addition, I will do minimal testing and merge it tomorrow.

**Comment by gleb-sevruk** [comment]
Can you actually run async test? I got
```
        if events._get_running_loop() is not None:
>           raise RuntimeError(
                'Cannot run the event loop while another loop is running')
E           RuntimeError: Cannot run the event loop while another loop is running
```

And need to dig deeper

**Comment by accoleon** [comment]
I did - however the actual running of the async tests required `nest_asyncio` as described in https://github.com/gleb-sevruk/pycrunch-engine/issues/52#issuecomment-908045411 - I didn't look further into the async system unfortunately. That will come next time!

**Comment by gleb-sevruk** [comment]
I got it working via next-asyncio
in pycrunch/multiprocess_child_main.py
```
import nest_asyncio
nest_asyncio.apply()
```

preparing a fix

**Comment by gleb-sevruk** [comment]
Seems up and running now:
https://github.com/gleb-sevruk/pycrunch-engine/pull/101

**Comment by accoleon** [comment]
🙌

**Comment by gleb-sevruk** [comment]
Thanks a lot; Version 1.6.1 Is published; Let me know about the experience.

https://pypi.org/project/pycrunch-engine/1.6.1/

**Comment by gleb-sevruk** [comment]
You will need to enable plugins in `.pycrunch.config` for this to work
```
engine:
  load-pytest-plugins: true
```

**Comment by accoleon** [comment]
Yep! Just tested 1.6.1 and works great. Pretty awesome, I loved ncrunch when I was working in .NET and have been looking for something for Python ever since!

**Comment by vegaroy13** [comment]
Oh Thank You. Just update to back front last updates (1.6.1) and works over python 3.10. Previous versions of python will fail due to syntax updated code not supported.

**Comment by gleb-sevruk** [comment]
@vegaroy13 
Oh I see what you mean

```
[98109] 2023-10-17 14:42:45,834 - pycrunch.discovery.ast_discovery - ERROR -  parse test_one.py failed with exception: unsupported operand type(s) for |: 'type' and 'type'
Traceback (most recent call last):
  File "/Users/gleb/venv/pycrunch_161_39_testing/lib/python3.9/site-packages/pycrunch/discovery/ast_discovery.py", line 68, in find_tests_in_folder
    tests_found = self.load_tests_from_ast_representation(ast_tree)
  File "/Users/gleb/venv/pycrunch_161_39_testing/lib/python3.9/site-packages/pycrunch/discovery/ast_discovery.py", line 98, in load_tests_from_ast_representation
    def process_function_def(func: ast.FunctionDef | ast.AsyncFunctionDef) -> List[str]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
[98109] 2023-10-17 14:42:45,835 - pycrunch.discovery.ast_discovery - INFO -  Time spent parsing AST : 0.0 seconds
```

I will do another version with `typing.Union` to make sure it can still work on 3.9

**Comment by gleb-sevruk** [comment]
Version 1.6.2 uploaded to pip; should resolve compatibility issues with Python 3.9

**Pull request closed without merging**
